version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./models:/app/models
    ports:
      - "8000:8000"
    networks:
      - ml-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/templates:/usr/share/nginx/html
      - ./frontend/static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
